name: Image Classification DenseNet Train
id: 8a04faa8-7e11-4205-9e1b-9aa9809ba83e
category: Machine Learning\Train
description: Creates a pretrained DenseNet for image classification and finetunes it
inputs:
- name: Model path
  type: ModelFolder
  port: True
  description: model_path
- name: Data path
  type: GenericFolder
  port: True
  description: data_path
- name: Model type
  type: Mode
  default: 'densenet201'
  description: model_type
  options:
    - 'densenet201'
    - 'densenet169'
    - 'densenet161'
    - 'densenet121'
- name: Pretrained
  type: Boolean
  default: True
  description: pretrained
- name: Memory efficient
  type: Boolean
  default: False
  description: memory_efficient
- name: Num of classes
  type: Int
  default: 3
  description: num of classes
- name: Epochs
  type: Int
  default: 7
  description: epochs
- name: Batch size
  type: Int
  default: 16
  description: batch_size
- name: Learning rate
  type: Float
  default: 0.001
  description: learning_rate
- name: Random seed
  type: Int
  default: 1
  description: random_seed
outputs:
- name: Save path
  type: ModelFolder
  description: save_path
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: True
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.3
      - pip:
        - fire==0.1.3
        - scipy==1.2.1
        - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
        - https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
        - git+https://github.com/StudioCommunity/CustomModules.git@migu/NewYamlTest#subdirectory=builtin-models
        - git+https://github.com/RichardZhaoW/CustomModules-1.git@master#subdirectory=azureml-custom-module-examples/image-classification-densenet
    command:
    - python
    - -m
    - imgclsdensenet.train
    args:
    - --model_path
    - inputValue: Model path
    - --data_path
    - inputValue: Data path
    - --model_type
    - inputValue: Model type
    - --pretrained
    - inputValue: Pretrained
    - --memory_efficient
    - inputValue: Memory efficient
    - --num_classes
    - inputValue: Num of classes
    - --epochs
    - inputValue: Epochs
    - --batch_size
    - inputValue: Batch size
    - --learning_rate
    - inputValue: Learning rate
    - --random_seed
    - inputValue: Random seed
    - --save_path
    - outputPath: Save path
