name: DetSegFB Train
id: a0743888-fb90-4bfc-83f0-bd4a9bcd1aa6
category: Machine Learning\Train
description: object detection and instance segmentation by facebook research
inputs:
- name: Trained model
  type: ModelFolder
  port: True
  description: Trained model folder
- name: Config file
  type: Mode
  default: "e2e_mask_rcnn_X_101_32x8d_FPN_1x_caffe2.yaml"
  description: config file name
  options:
    - e2e_mask_rcnn_X_101_32x8d_FPN_1x_caffe2.yaml
    - e2e_faster_rcnn_X_101_32x8d_FPN_1x_caffe2.yaml
outputs:
- name: Output trained model
  type: ModelFolder
  description: The output model directory
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: True
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - ipython
      - python=3.6.2
      - pip:
        - fire==0.1.3
    command:
    - python
    - -m
    - detsegfb.train
    args:
    - --model_folder
    - inputValue: Trained model
    - --config_filename
    - inputValue: Config file
    - --out_model_folder
    - outputPath: Output trained model